### ISSUE TITLE
error: "no persistent term stored with this key: UUIDv7.Clock"

### ISSUE THREAD

**Issue by pmarreck** [ryanwinchester/uuidv7#8]
Did I forget to add a config? (or is there one missing from the docs?)

```
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: no persistent term stored with this key

    :persistent_term.get(UUIDv7.Clock)
    (uuid_v7 0.5.0) lib/clock.ex:23: UUIDv7.Clock.next/1
    (uuid_v7 0.5.0) lib/uuidv7.ex:61: UUIDv7.bingenerate/0
    (uuid_v7 0.5.0) lib/uuidv7.ex:45: UUIDv7.generate/0
    (ecto 3.10.3) lib/ecto/repo/schema.ex:974: anonymous fn/2 in Ecto.Repo.Schema.autogenerate_changes/3
    (elixir 1.16.2) lib/enum.ex:4326: Enum.flat_map_list/2
    (ecto 3.10.3) lib/ecto/repo/schema.ex:364: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (ecto 3.10.3) lib/ecto/repo/schema.ex:273: Ecto.Repo.Schema.insert!/4
```

**Comment by ryanwinchester** [comment]
Thanks for that, it's a good catch. It's missing from docs.

Can you try adding this to your `config/config.exs`?

```elixir
config :app, App.Repo, start_apps_before_migration: [:uuid_v7]
```

**Comment by pmarreck** [comment]
That fixed it! Thanks!
